# Generated by Django 5.1.6 on 2025-02-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="A short description of the recipe"),
                ),
                ("ingredients", models.TextField(help_text="List the ingredients")),
                (
                    "instructions",
                    models.TextField(help_text="Step-by-step instructions"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of an image for the recipe",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
